version: "3.8"

services:
  postgres_app:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: perfume
    ports:
      - '5432:5432'
    networks:
      - arquitectura

  back:
    build: .
    depends_on:
      - postgres_app
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - arquitectura  
      
  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - postgres_app
      - back
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      - arquitectura
    
  bucket:
    image: minio/minio
    entrypoint: "minio server /data --console-address :9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: S1ngu1ar
    networks:
      - arquitectura
  
  #https://stackoverflow.com/a/66485256
  modifybuckets:
    image: minio/mc
    volumes:
      - './scripts:/scripts'
      - './min.io/init_scripts:/init_scripts'
      - './min.io/images:/images'
    depends_on:
      - bucket
    entrypoint: "/init_scripts/init_bucket.sh"
    networks:
      - arquitectura

  smtp4dev:
    image: rnwood/smtp4dev:v3.1
    restart: always
    volumes:
      - smtp4dev-data:/smtp4dev
    ports:
      - '8081:80'
      - '25:25'
      - '143:143'
    environment:
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      ServerOptions__HostName: smtp4dev
    networks:
      - arquitectura

networks:
  arquitectura:
    driver: bridge

volumes:
  min.io:
  frontend:
  smtp4dev-data:
  scripts:
